### ISSUE TITLE
Missing ',' on struct declarations absorbs next item silently 

### ISSUE THREAD

**Issue by Luctins** [jcaesar/structstruck#4] opened 2022-11-29 20:49 UTC
## Expected Behaviour:
A error would be raised when there's a missing ',' after a struct declaration

## MWE :
(using `structstruck = "0.3"`)
```rust
#![allow(unused)]
structstruck::strike!{
    #[strikethrough[derive(Debug, Default)]]
    struct Correct {
        not_eater: struct {
            stomach: (),
        },
        not_eaten: struct {
            apple: bool,
        }
    }
}

structstruck::strike!{
    #[strikethrough[derive(Debug, Default)]]
    struct Incorrect {
        eater: struct {
            stomach: (),
        } // notice the missing comma
        eaten: struct {
            apple: bool,
        }
    }
}

fn main() {
    println!("correct: {:?}", Correct::default());
    println!("incorrect: {:?}", Incorrect::default());
}

```
and the output is:
```rust
correct: Correct { not_eater: NotEater { stomach: () }, not_eaten: NotEaten { apple: false } }
incorrect: Incorrect { eater: Eater { stomach: () } }
```

## Observations

@jcaesar, if you have a vague idea of how to fix this, you can try to guide me, as I would like to fix this (to learn more about derive macros).

**Comment by jcaesar** [comment] 2022-11-30 00:45
My usual entrypoint to this kind of debugging is to
1. Add a (hopefully failing) test with the broken struct. (Then you can ignore the proc macro part and debug the test like its normal rust code.)
2. Add a `println!("{parsed:#?}")` [here](https://github.com/jcaesar/structstruck/blob/399b837e4790dedb3f689f6c76688581d2852178/src/imp.rs#L55-L56) to see how venial transformed the tokens into rust structs. (Or well, if you've got a debugger that doesn't consist of `println` and thinking meat, use that.)

(So I'm not sure whether this will help you understand derive/proc macros. The problem is in normal rust code. Then again, proc macros are significantly less magic than you think: They get [compiled to a dynamic libary](https://github.com/jcaesar/structstruck/blob/399b837e4790dedb3f689f6c76688581d2852178/Cargo.toml#L12-L13) which rustc loads at runtime and calls the [entrypoint](https://github.com/jcaesar/structstruck/blob/399b837e4790dedb3f689f6c76688581d2852178/src/lib.rs#L222-L223) with the token stream. This flat-ish stream then gets parsed into easy to work-with rust structs by `syn` (usual) or `venial` (here). There's some messy details with `proc_macro` vs `proc_macro2` because the structs that rustc provded are not nice to work with. Other than that, fasterthanlime has a good writeup of the gory [details](https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions).)

<details><summary>Spoiler</summary>

I think what's happening here is that venial doesn't parse types, so the entire `… } /* missing comma */ eaten: struct …` is interpreted as the type of `eater`. I haven't looked at it deeply yet, but probably structstruck should error on finding two `is_decl_kw` [here](https://github.com/jcaesar/structstruck/blob/399b837e4790dedb3f689f6c76688581d2852178/src/imp.rs#L294).

**Comment by jcaesar** [comment] 2022-11-30 02:47
Thinking about it: similar bugs might also exist for `struct Foo { foo: Result<struct O {} struct E {}> }`. I'll check that.

**Comment by Luctins** [comment] 2022-11-30 13:34
Thanks a lot, I'll look into it when I can.

So far I've opened the issue to document it, but I'm not sure when I will be able to try my hand at fixing it. It's just a little annoying to have (and to spot) when you don't know about it, and rust usually is great at warning you about this kind of 'obvious' stumbling blocks.

Maybe add a note on the main docs.rs page about this so other people using the library are aware of it?

**Comment by jcaesar** [comment] 2022-12-01 00:08
I don't think a fix would be too complicated. I hope I'll have time to have a look this weekend.

**Comment by halotroop2288** [comment] 2023-02-21 16:57
> I don't think a fix would be too complicated. I hope I'll have time to have a look this weekend.

*3 months go by* 😹

**Comment by jcaesar** [comment] 2023-02-22 04:39
Its fixed in this repo. Its fixed in venial, too, and I was kind of hoping they'd do a release. Oh well, I guess I'll do one.

**Closed as completed** 2023-02-22 11:15 UTC
